from .unsplash import UnsplashScraper
from .pixabay import PixabayScraper
from .wallhaven import WallhavenScraper
from .vecteezy import VecteezyScraper
from .wallpapercave import WallpaperCaveScraper
from .wallpapers_com import WallpapersComScraper
from .wallpapersafari import WallpaperSafariScraper
from .uhdpaper import UHDPaperScraper
from .pixelstalk import PixelstalkScraper
from .stocksnap import StockSnapScraper